version: "3.9"

services:
  app:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        yarn
        yarn start